
%Part 0
x = randn(1064,1);
numcoef = 1;
denomcoef = [1, 0.9];
y = filter(numcoef, denomcoef, x);
y = y(41:end);
x = x(41:end);
time = 41:1064;

%Part 1
[h,w] = freqz([1],[1 0.9], 512);
figure
plot(w/(2*pi), abs(h).^2,'b')
hold on
%Part 2 
pgmy = pgm(y);
pgmy = pgmy(1:length(pgmy)/2);
plot(w/(2*pi),pgmy,'r')
hold off
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('PSD and Periodogram of sequence generated by AR(1) model')
legend('exact PSD','Periodogram')

%Part 3
figure
plot(w/(2*pi), abs(h).^2,'b')
hold on
plot(w/(2*pi),pgmy,'r')
hold off
xlim([0.4,0.5]);
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('PSD and Periodogram of sequence generated by AR(1) model')
legend('exact PSD','Periodogram')


%Part 4
Ry = xcorr(y);
lengthRy = length(Ry);
Ry0 = Ry(1024);
Ry1 = Ry(1024+1);
a1 = -Ry1/Ry0;
variancey = (Ry0 + a1*Ry1)/1024;
[hy,wy] = freqz([variancey],[1 a1], 512);
figure
plot(w/(2*pi), abs(h).^2,'b')
hold on
plot(w/(2*pi),pgmy,'r')
plot(wy/(2*pi), abs(hy).^2,'y')
hold off
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Exact PSD, Periodogram and Model-based PSD estimate of sequence generated by AR(1) model')
legend('exact PSD','Periodogram','Model-based PSD')


%Part 5
load sunspot.dat 
sunspotdata = sunspot(:,2);
sunspotdata250 = sunspotdata(1:250);

rangevalid = 1:length(sunspotdata250)/2;
pgmsunspot = pgm(sunspotdata250);
pgmsunspot = pgmsunspot(1:length(sunspotdata250)/2);
figure
plot(rangevalid / 250, pgmsunspot,'r')
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Periodogram of sunspot time series')
Rsunspot = xcorr(sunspotdata250);
lengthRsunspot = length(Rsunspot);
maxvalue = max(Rsunspot);
Rsunspot0 = Rsunspot(250);
Rsunspot1 = Rsunspot(250+1);
asunspot = -Rsunspot1/Rsunspot0;
variancesunspot = (Rsunspot0 + asunspot*Rsunspot1) / 250; 
[hsunspot,wsunspot] = freqz([variancesunspot],[1 asunspot], 512);
figure
plot(wsunspot/(2*pi), abs(hsunspot).^2)
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Model-based PSD estimate of sunspot time series')

sunspotdata250mc = sunspotdata250 - mean(sunspotdata250);
pgmsunspotmc = pgm(sunspotdata250mc);
pgmsunspotmc = pgmsunspotmc(1:length(sunspotdata250mc)/2);
figure
plot(rangevalid / 250, pgmsunspotmc,'r')
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Periodogram of mean-centred sunspot time series')
Rsunspotmc = xcorr(sunspotdata250mc);
lengthRsunspotmc = length(Rsunspotmc);
Rsunspotmc0 = Rsunspotmc(250);
Rsunspotmc1 = Rsunspotmc(250+1);
asunspotmc = -Rsunspotmc1/Rsunspotmc0;
variancesunspotmc = (Rsunspotmc0 + asunspotmc*Rsunspotmc1) / 250; 
[hsunspotmc,wsunspotmc] = freqz([variancesunspotmc],[1 asunspotmc], 512);
figure
plot(wsunspotmc/(2*pi), abs(hsunspotmc).^2)
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Model-based PSD estimate of mean-centred sunspot time series')

ar1 = ar(sunspotdata250,1);
ar2 = ar(sunspotdata250,2);
ar10 = ar(sunspotdata250,10);
sunspotar1 = predict(ar1,sunspotdata250,3);
sunspotar2 = predict(ar2,sunspotdata250,3);
sunspotar10 = predict(ar10,sunspotdata250,3);
pgmsunspotar1 = pgm(sunspotar1);
pgmsunspotar1 = pgmsunspotar1(1:length(sunspotar1)/2);
pgmsunspotar2 = pgm(sunspotar2);
pgmsunspotar2 = pgmsunspotar2(1:length(sunspotar2)/2);
pgmsunspotar10 = pgm(sunspotar1);
pgmsunspotar10 = pgmsunspotar10(1:length(sunspotar10)/2);

figure
plot(rangevalid / 250, pgmsunspotar1)
hold on
plot(rangevalid / 250, pgmsunspotar2)
plot(rangevalid / 250, pgmsunspotar10)
hold off
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Periodogram of sunspot time series for different AR model orders')
legend('AR(1)', 'AR(2)', 'AR(10)')

Rsunspotar1 = xcorr(sunspotar1);
Rsunspotar1_0 = Rsunspotar1(250);
Rsunspotar1_1 = Rsunspotar1(250+1);
asunspotar1 = -Rsunspotar1_1/Rsunspotar1_0;
variancesunspotar1 = (Rsunspotar1_0 + asunspotar1*Rsunspotar1_1) / 250; 
[hsunspotar1,wsunspotar1] = freqz([variancesunspotar1],[1 asunspotar1], 512);
Rsunspotar2 = xcorr(sunspotar2);
Rsunspotar2_0 = Rsunspotar2(250);
Rsunspotar2_1 = Rsunspotar2(250+1);
asunspotar2 = -Rsunspotar2_1/Rsunspotar2_0;
variancesunspotar2 = (Rsunspotar2_0 + asunspotar2*Rsunspotar2_1) / 250; 
[hsunspotar2,wsunspotar2] = freqz([variancesunspotar2],[1 asunspotar2], 512);
Rsunspotar10 = xcorr(sunspotar10);
Rsunspotar10_0 = Rsunspotar10(250);
Rsunspotar10_1 = Rsunspotar10(250+1);
asunspotar10 = -Rsunspotar10_1/Rsunspotar10_0;
variancesunspotar10 = (Rsunspotar10_0 + asunspotar10*Rsunspotar10_1) / 250; 
[hsunspotar10,wsunspotar10] = freqz([variancesunspotar10],[1 asunspotar10], 512);

figure
plot(wsunspotar1/(2*pi), abs(hsunspotar1).^2)
hold on
plot(wsunspotar2/(2*pi), abs(hsunspotar2).^2)
plot(wsunspotar10/(2*pi), abs(hsunspotar10).^2)
xlabel('Normalised Frequency')
ylabel('Magnitude')
title('Model-based PSD estimate of sunspot time series for different AR model orders')
legend('AR(1)', 'AR(2)', 'AR(10)')

